# Generated by Django 5.2.14 on 2026-06-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('MARKETPLACE', 'Marketplace'), ('BOUTIQUE', 'Boutique')], default='MARKETPLACE', max_length=20),
        ),
    ]
