# Generated by Django 5.2.14 on 2026-05-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(upload_to='shop_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
