# Generated by Django 5.2.14 on 2026-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='condition',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('excellent', 'Excellent état'), ('bon', 'Bon état')], default='excellent', max_length=20),
        ),
    ]
