# Generated by Django 5.2.14 on 2026-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='link_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Nouveau Message'), ('achat', 'Vente effectuée'), ('commentaire', 'Nouveau Commentaire'), ('like', 'Nouveau Like')], default='like', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default='Nouvelle notification'),
            preserve_default=False,
        ),
    ]
