# Generated by Django 5.2.14 on 2026-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Nouveau Message'), ('achat', 'Vente effectuée'), ('comment', 'Nouveau Commentaire'), ('like', 'Nouveau Like')], max_length=20),
        ),
    ]
