# Generated by Django 5.2.15 on 2026-06-12 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nom entreprise')),
                ('manager_name', models.CharField(max_length=180, verbose_name='responsable')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('hectares', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="nombre d'hectares")),
                ('subscription', models.CharField(choices=[('starter', 'Suivi initial client'), ('growth', 'Croissance Drone + IA'), ('large', 'Grandes exploitations')], default='starter', max_length=30, verbose_name='abonnement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='pending', max_length=30, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'client entreprise',
                'verbose_name_plural': 'clients entreprises',
                'db_table': 'company_clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='maladie')),
                ('crop', models.CharField(blank=True, max_length=140, verbose_name='culture')),
                ('symptoms', models.TextField(blank=True, verbose_name='symptomes')),
                ('causes', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Modere'), ('high', 'Eleve'), ('critical', 'Critique')], default='medium', max_length=30, verbose_name='niveau de risque')),
            ],
            options={
                'verbose_name': 'maladie',
                'verbose_name_plural': 'maladies',
                'db_table': 'diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nom drone')),
                ('model', models.CharField(max_length=140, verbose_name='modele')),
                ('serial_number', models.CharField(max_length=120, unique=True, verbose_name='numero serie')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_mission', 'En mission'), ('maintenance', 'Maintenance')], default='available', max_length=30, verbose_name='etat')),
                ('flight_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vols')),
                ('maintenance_date', models.DateField(blank=True, null=True, verbose_name='date de maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'drone',
                'verbose_name_plural': 'drones',
                'db_table': 'drones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='nom complet')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('drone_pilot', 'Pilote drone'), ('ai_technician', 'Technicien IA'), ('field_agent', 'Agent terrain'), ('sales', 'Commercial')], max_length=40, verbose_name='role')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('field', 'Sur terrain'), ('off', 'Indisponible')], default='active', max_length=30, verbose_name='statut')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name="date d'arrivee")),
            ],
            options={
                'verbose_name': 'employe',
                'verbose_name_plural': 'employes',
                'db_table': 'employees',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportantAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='alerte')),
                ('message', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('info', 'Information'), ('warning', 'Attention'), ('urgent', 'Urgent')], default='info', max_length=30)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resolue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'alerte importante',
                'verbose_name_plural': 'alertes importantes',
                'db_table': 'important_alerts',
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='nom complet')),
                ('phone', models.CharField(max_length=40, unique=True, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date inscription')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'client mobile',
                'verbose_name_plural': 'clients mobile',
                'db_table': 'mobile_users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, unique=True, verbose_name='facture')),
                ('subscription', models.CharField(blank=True, max_length=160, verbose_name='abonnement')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant facture')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='montant paye')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiel'), ('paid', 'Paye'), ('overdue', 'En retard'), ('cancelled', 'Annule')], default='pending', max_length=30, verbose_name='statut')),
                ('issued_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='date emission')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='date echeance')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='date paiement')),
                ('pdf', models.FileField(blank=True, upload_to='invoices/', verbose_name='facture PDF')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='operations.companyclient')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'db_table': 'invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, max_length=80)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operations.mobileuser')),
            ],
            options={
                'verbose_name': 'notification mobile',
                'verbose_name_plural': 'notifications mobile',
                'db_table': 'mobile_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nom parcelle')),
                ('surface_hectares', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='surface')),
                ('crop', models.CharField(max_length=140, verbose_name='culture')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('general_state', models.CharField(choices=[('healthy', 'Bon'), ('watch', 'Sous surveillance'), ('risk', 'Risque'), ('critical', 'Critique')], default='watch', max_length=30, verbose_name='etat general')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='operations.companyclient')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'parcelles',
                'db_table': 'parcels',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_date', models.DateTimeField(verbose_name='date')),
                ('status', models.CharField(choices=[('planned', 'Planifiee'), ('in_progress', 'En cours'), ('completed', 'Terminee'), ('cancelled', 'Annulee')], default='planned', max_length=30, verbose_name='statut')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='operations.companyclient')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='operations.drone')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='operations.employee')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='operations.parcel')),
            ],
            options={
                'verbose_name': 'mission terrain',
                'verbose_name_plural': 'missions terrain',
                'db_table': 'field_missions',
                'ordering': ['-mission_date'],
            },
        ),
        migrations.CreateModel(
            name='AiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('drone', 'Drone')], max_length=20, verbose_name='origine')),
                ('image', models.FileField(blank=True, upload_to='analyses/', verbose_name='image')),
                ('image_url', models.URLField(blank=True, verbose_name='image externe')),
                ('detected_plant', models.CharField(blank=True, max_length=140, verbose_name='plante detectee')),
                ('detected_disease', models.CharField(blank=True, max_length=180, verbose_name='maladie detectee')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='niveau de confiance')),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Modere'), ('high', 'Eleve'), ('critical', 'Critique'), ('unknown', 'A confirmer')], default='unknown', max_length=30, verbose_name='niveau de risque')),
                ('provider', models.CharField(choices=[('plantnet', 'Pl@ntNet'), ('plant_id', 'Plant.id'), ('crop_health', 'Crop.Health'), ('plant_village', 'PlantVillage'), ('plant_doc', 'PlantDoc'), ('agricheck', 'Agricheck')], default='agricheck', max_length=40, verbose_name='source IA')),
                ('raw_ai_response', models.JSONField(blank=True, null=True, verbose_name='reponse IA brute')),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date analyse')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='operations.companyclient')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='operations.disease')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='operations.fieldmission')),
                ('mobile_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='operations.mobileuser')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='operations.parcel')),
            ],
            options={
                'verbose_name': 'analyse IA',
                'verbose_name_plural': 'analyses IA',
                'db_table': 'ai_analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='rapport client')),
                ('ai_result', models.TextField(blank=True, verbose_name='resultat IA')),
                ('recommended_treatment', models.TextField(blank=True, verbose_name='traitement recommande')),
                ('pdf', models.FileField(blank=True, upload_to='reports/pdfs/', verbose_name='PDF telechargeable')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie')], default='draft', max_length=30, verbose_name='statut')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='operations.aianalysis')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='operations.companyclient')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='operations.parcel')),
            ],
            options={
                'verbose_name': 'rapport',
                'verbose_name_plural': 'rapports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_recommended', models.TextField(blank=True, verbose_name='produit recommande')),
                ('dosage', models.CharField(blank=True, max_length=180)),
                ('frequency', models.CharField(blank=True, max_length=180, verbose_name='frequence')),
                ('prevention', models.TextField(blank=True, verbose_name='conseils de prevention')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='operations.disease')),
            ],
            options={
                'verbose_name': 'traitement',
                'verbose_name_plural': 'traitements',
                'db_table': 'treatments',
                'ordering': ['disease__name'],
            },
        ),
    ]
