# Generated by Django 5.2.15 on 2026-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyclient',
            name='external_client_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='identifiant client externe'),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('card', 'Carte bancaire'), ('check', 'Cheque client')], max_length=40, verbose_name='moyen de paiement'),
        ),
        migrations.AddField(
            model_name='companyclient',
            name='subscription_price_xof',
            field=models.PositiveIntegerField(default=75000, verbose_name='prix mensuel'),
        ),
    ]
