# Generated by Django 5.2.15 on 2026-06-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_companyclient_external_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_missions', to='operations.companyclient'),
        ),
        migrations.AlterField(
            model_name='fieldmission',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drone_missions', to='operations.drone'),
        ),
        migrations.AlterField(
            model_name='fieldmission',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_missions', to='operations.parcel'),
        ),
        migrations.AlterField(
            model_name='fieldmission',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilote_missions', to='operations.employee'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_reports', to='operations.companyclient'),
        ),
        migrations.AlterField(
            model_name='report',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to='operations.parcel'),
        ),
    ]
