services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    environment:
      - DOCKER_API_VERSION=1.41
    networks:
      - proxy-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`www.monmarche-mali.com`) || Host(`monmarche-mali.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"

networks:
  proxy-net:
    external: true
