from decimal import Decimal

from django.utils import timezone

from .models import (
    AiAnalysis,
    CompanyClient,
    Disease,
    Drone,
    Employee,
    FieldMission,
    Invoice,
    MobileUser,
    Parcel,
    Report,
    Treatment,
)


def money(value):
    value = value or Decimal("0")
    return f"{value:,.0f} FCFA".replace(",", " ")


def date_value(value):
    if not value:
        return ""
    if hasattr(value, "strftime"):
        return timezone.localtime(value).strftime("%d/%m/%Y %H:%M") if hasattr(value, "hour") else value.strftime("%d/%m/%Y")
    return str(value)


ENTITY_CONFIG = {
    "mobile": {
        "label": "Clients mobile",
        "title": "Clients de l'application mobile",
        "subtitle": "Utilisateurs inscrits, scans effectues, analyses realisees et maladies detectees.",
        "model": MobileUser,
        "fields": ["full_name", "phone", "email", "avatar_url", "is_active", "created_at"],
        "search": ["full_name", "phone", "email"],
        "filter_field": "is_active",
        "filter_options": [("1", "Actifs"), ("0", "Inactifs")],
        "columns": [
            ("Nom", lambda item: item.full_name),
            ("Telephone", lambda item: item.phone),
            ("Email", lambda item: item.email or ""),
            ("Scans", lambda item: item.scan_count),
            ("Analyses", lambda item: item.scan_count),
            ("Maladies detectees", lambda item: item.disease_count),
            ("Inscription", lambda item: date_value(item.created_at)),
        ],
    },
    "companies": {
        "label": "Clients entreprises",
        "title": "Clients entreprises",
        "subtitle": "Entreprises, responsables, hectares, parcelles suivies, abonnements et factures.",
        "model": CompanyClient,
        "fields": [
            "name",
            "manager_name",
            "phone",
            "email",
            "address",
            "hectares",
            "subscription",
            "subscription_price_xof",
            "payment_method",
            "status",
            "external_client_id",
        ],
        "search": ["name", "manager_name", "phone", "email"],
        "filter_field": "status",
        "filter_options": CompanyClient.Status.choices,
        "columns": [
            ("Entreprise", lambda item: item.name),
            ("Responsable", lambda item: item.manager_name),
            ("Telephone", lambda item: item.phone),
            ("Email", lambda item: item.email),
            ("Hectares", lambda item: item.hectares),
            ("Parcelles", lambda item: item.parcels.count()),
            ("Abonnement", lambda item: item.get_subscription_display()),
            ("Moyen paiement", lambda item: item.get_payment_method_display() if item.payment_method else ""),
            ("Factures impayees", lambda item: money(item.unpaid_total)),
        ],
    },
    "drones": {
        "label": "Drones",
        "title": "Drones Agricheck",
        "subtitle": "Flotte, modele, etat, nombre de vols et maintenance.",
        "model": Drone,
        "fields": ["name", "model", "serial_number", "status", "flight_count", "maintenance_date"],
        "search": ["name", "model", "serial_number"],
        "filter_field": "status",
        "filter_options": Drone.Status.choices,
        "columns": [
            ("Nom drone", lambda item: item.name),
            ("Modele", lambda item: item.model),
            ("Etat", lambda item: item.get_status_display()),
            ("Nombre de vols", lambda item: item.flight_count),
            ("Maintenance", lambda item: date_value(item.maintenance_date)),
        ],
    },
    "missions": {
        "label": "Missions terrain",
        "title": "Missions terrain",
        "subtitle": "Client concerne, parcelle, drone utilise, pilote, date et statut.",
        "model": FieldMission,
        "fields": ["company", "parcel", "drone", "pilot", "mission_date", "status", "notes"],
        "search": ["company__name", "parcel__name", "drone__name", "pilot__full_name"],
        "filter_field": "status",
        "filter_options": FieldMission.Status.choices,
        "select_related": ["company", "parcel", "drone", "pilot"],
        "columns": [
            ("Client", lambda item: item.company.name),
            ("Parcelle", lambda item: item.parcel.name),
            ("Drone", lambda item: item.drone.name),
            ("Pilote", lambda item: item.pilot.full_name if item.pilot else ""),
            ("Date", lambda item: date_value(item.mission_date)),
            ("Statut", lambda item: item.get_status_display()),
        ],
    },
    "analyses": {
        "label": "Analyses IA",
        "title": "Analyses IA drone",
        "subtitle": "Captures drone recues, analyse IA lancee par Agricheck, resultats et niveau de risque.",
        "model": AiAnalysis,
        "base_filter": {"source": AiAnalysis.Source.DRONE},
        "fields": [
            "company",
            "parcel",
            "mission",
            "image",
            "image_url",
            "detected_plant",
            "disease",
            "detected_disease",
            "confidence",
            "risk_level",
            "provider",
            "raw_ai_response",
            "analyzed_at",
        ],
        "search": ["company__name", "parcel__name", "mission__drone__name", "detected_plant", "detected_disease", "disease__name"],
        "filter_field": "risk_level",
        "filter_options": AiAnalysis.RiskLevel.choices,
        "select_related": ["company", "parcel", "mission", "mission__drone", "disease"],
        "columns": [
            ("Client", lambda item: item.client_label),
            ("Parcelle", lambda item: item.parcel.name if item.parcel else ""),
            ("Drone", lambda item: item.mission.drone.name if item.mission else ""),
            ("Image", lambda item: "Recue" if item.image or item.image_url else "Manquante"),
            ("Statut IA", lambda item: "Analysee" if item.disease_label else "A analyser"),
            ("Plante detectee", lambda item: item.detected_plant),
            ("Maladie detectee", lambda item: item.disease_label),
            ("Confiance", lambda item: f"{item.confidence}%" if item.confidence is not None else ""),
            ("Risque", lambda item: item.get_risk_level_display()),
            ("Date", lambda item: date_value(item.analyzed_at)),
        ],
    },
    "reports": {
        "label": "Rapports",
        "title": "Rapports",
        "subtitle": "Rapports client et parcelle, resultat IA, traitement recommande, PDF et publication.",
        "model": Report,
        "fields": ["company", "parcel", "analysis", "title", "ai_result", "recommended_treatment", "pdf", "status"],
        "search": [
            "title",
            "company__name",
            "parcel__name",
            "ai_result",
            "analysis__detected_plant",
            "analysis__detected_disease",
            "analysis__disease__name",
        ],
        "filter_field": "status",
        "filter_options": Report.Status.choices,
        "select_related": ["company", "parcel", "analysis", "analysis__disease"],
        "columns": [
            ("Rapport client", lambda item: item.title),
            ("Client", lambda item: item.company.name),
            ("Parcelle", lambda item: item.parcel.name if item.parcel else ""),
            ("Resultat analyse", lambda item: item.analysis_result_display[:120]),
            ("Traitement", lambda item: item.recommended_treatment_display[:90]),
            ("PDF", lambda item: "Disponible" if item.pdf else ""),
            ("Statut", lambda item: item.get_status_display()),
            ("Envoi client", lambda item: "Envoye au client" if item.status == Report.Status.PUBLISHED else "Non publie"),
        ],
    },
    "treatments": {
        "label": "Traitements",
        "title": "Traitements",
        "subtitle": "Maladie, produit recommande, dosage, frequence et prevention.",
        "model": Treatment,
        "fields": ["disease", "product_recommended", "dosage", "frequency", "prevention"],
        "search": ["disease__name", "product_recommended", "prevention"],
        "select_related": ["disease"],
        "columns": [
            ("Maladie", lambda item: item.disease.name),
            ("Produit recommande", lambda item: item.product_recommended[:80]),
            ("Dosage", lambda item: item.dosage),
            ("Frequence", lambda item: item.frequency),
            ("Conseils de prevention", lambda item: item.prevention[:90]),
        ],
    },
    "payments": {
        "label": "Paiements",
        "title": "Paiements et abonnements",
        "subtitle": "Factures, montants payes, impayes, revenus mensuels et revenus annuels.",
        "model": Invoice,
        "fields": [
            "company",
            "number",
            "subscription",
            "amount_total",
            "amount_paid",
            "status",
            "issued_at",
            "due_date",
            "paid_at",
            "pdf",
        ],
        "search": ["number", "company__name", "subscription"],
        "filter_field": "status",
        "filter_options": Invoice.Status.choices,
        "select_related": ["company"],
        "columns": [
            ("Facture", lambda item: item.number),
            ("Client", lambda item: item.company.name),
            ("Abonnement", lambda item: item.subscription),
            ("Montant paye", lambda item: money(item.amount_paid)),
            ("Montant impaye", lambda item: money(item.amount_unpaid)),
            ("Statut", lambda item: item.get_status_display()),
            ("Envoi client", lambda item: "Visible client"),
        ],
    },
    "employees": {
        "label": "Employes",
        "title": "Employes",
        "subtitle": "Administrateurs, pilotes drones, techniciens IA, agents terrain et commerciaux.",
        "model": Employee,
        "fields": ["full_name", "role", "phone", "email", "status", "hired_at"],
        "search": ["full_name", "phone", "email"],
        "filter_field": "role",
        "filter_options": Employee.Role.choices,
        "columns": [
            ("Employe", lambda item: item.full_name),
            ("Role", lambda item: item.get_role_display()),
            ("Telephone", lambda item: item.phone),
            ("Email", lambda item: item.email),
            ("Statut", lambda item: item.get_status_display()),
        ],
    },
    "parcels": {
        "label": "Parcelles",
        "title": "Parcelles suivies",
        "subtitle": "Parcelles des clients entreprises gerees par Agricheck.",
        "model": Parcel,
        "fields": ["company", "name", "surface_hectares", "crop", "gps_latitude", "gps_longitude", "general_state"],
        "search": ["company__name", "name", "crop"],
        "filter_field": "general_state",
        "filter_options": Parcel.State.choices,
        "select_related": ["company"],
        "columns": [
            ("Client", lambda item: item.company.name),
            ("Parcelle", lambda item: item.name),
            ("Surface", lambda item: item.surface_hectares),
            ("Culture", lambda item: item.crop),
            ("Etat", lambda item: item.get_general_state_display()),
        ],
    },
}
