# Generated by Django 5.2.15 on 2026-06-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_client_simplification_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'resultat Agricheck', 'verbose_name_plural': 'resultats Agricheck'},
        ),
    ]
