#version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - lakika_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lakika_db
      - POSTGRES_USER=lakika_user
      - POSTGRES_PASSWORD=lakika_password
    networks:
      - lakika-net

  web:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    # ports:  <-- Supprimé pour éviter le conflit de port 8000
    #   - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://lakika_user:lakika_password@db:5432/lakika_db
      - EMAIL_HOST_USER=kanezoumana643@gmail.com
      - EMAIL_HOST_PASSWORD=pmna chcq qzuq ypmo
      - ADMIN_EMAIL=kanezoumana643@gmail.com
    networks:
      - lakika-net
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lakika.rule=Host(`www.bouillon-lakika.com`) || Host(`bouillon-lakika.com`)"
      - "traefik.http.routers.lakika.entrypoints=websecure"
      - "traefik.http.routers.lakika.tls.certresolver=myresolver"
      - "traefik.http.services.lakika.loadbalancer.server.port=8000"
    restart: always

networks:
  lakika-net:
  proxy-net:
    external: true

volumes:
  media_volume:
  lakika_db_data:
