version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lakika.rule=Host(`www.bouillon-lakika.com`) || Host(`bouillon-lakika.com`)"
      - "traefik.http.routers.lakika.entrypoints=websecure"
      - "traefik.http.routers.lakika.tls.certresolver=myresolver"
      - "traefik.http.services.lakika.loadbalancer.server.port=8000"
    restart: always

networks:
  proxy-net:
    external: true

volumes:
  media_volume:
