# Generated by Django 5.2.14 on 2026-06-08 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('product_type', models.CharField(choices=[('BOUTIQUE', 'Article Boutique'), ('MARKETPLACE', 'Annonce Marketplace')], default='BOUTIQUE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
